apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1 
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-bitsnake-server
        image: francogallegosqu/backend-bitsnake-server:main
        ports:
        - containerPort: 80
      initContainers:
        - name: copyutil
          image: francogallegosqu/backend-bitsnake-server:main
          command:
            - cp
            - -n
            - /usr/local/bin/argocd-dex
            - /shared
        