apiVersion: v1
kind: Service
metadata:
  name: my-service-backend
spec:
  selector:
    deployment backend-bitsnake-server
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376