apiVersion: v1
kind: Service
metadata:
  name: my-service-backend
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376