apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-bitsnake-server
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-bitsnake-server
        image: francogallegosqu/backend-bitsnake-server:main
        ports:
        - containerPort: 80